phrase = 'Curso em Vídeo Python'
print(phrase.split())
print(phrase.upper())
print(phrase.lower())
print(phrase.capitalize())
print(phrase.title())
print(phrase.count('o'))
print(phrase.find('o'))
print(phrase.find('Curso'))
print(phrase.find('Android'))
print(phrase[5:])
print(phrase[::])
print(phrase[:10])
print('Curso' in phrase)
print(phrase.replace('Python','Android'))
phrase = '  Curso em Vídeo Python       '
print(phrase)
print(phrase.strip())
print(phrase.lstrip())
print(phrase.rstrip())
print(len(phrase.strip()))
print(len(phrase))